// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcoL1zFn-D6F-2Dtzj2FN28ak6KOG2PO0',
    appId: '1:276108436348:android:a66f8e899570022a6bbaf9',
    messagingSenderId: '276108436348',
    projectId: 'fridchen-app-58258',
    storageBucket: 'fridchen-app-58258.appspot.com',
    // googleAppID: '1:276108436348:android:a66f8e899570022a6bbaf9',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwUN1I8_GmiGmjQqDBs95OIdduSm9Q3lo',
    appId: '1:276108436348:ios:526d49e6db9c198e6bbaf9',
    messagingSenderId: '276108436348',
    projectId: 'fridchen-app-58258',
    storageBucket: 'fridchen-app-58258.appspot.com',
    iosClientId:
        '276108436348-ub5fmsiv738ja6qoe6876olc68buff8u.apps.googleusercontent.com',
    iosBundleId: 'com.example.fridchenApp',
    // googleAppID: '1:276108436348:ios:526d49e6db9c198e6bbaf9',
  );
}
